-- ============================================================
-- TECHSTORE - SUPABASE POSTGRESQL SCHEMA, RLS & AUDITORÍA ASFI
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Tabla Usuario
CREATE TABLE IF NOT EXISTS public.usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    telefono VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL DEFAULT '$2a$12$e8Yk1.K1K7w7oH1x3YFGe.a9GgN5W2WkSjC7zZ7a0P1Q9b8U5j9s6',
    rol VARCHAR(20) NOT NULL DEFAULT 'CLIENTE' CHECK (rol IN ('CLIENTE', 'ADMINISTRADOR')),
    fecha_registro DATE NOT NULL DEFAULT CURRENT_DATE
);

-- 2. Tabla Categoria
CREATE TABLE IF NOT EXISTS public.categoria (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    estado VARCHAR(15) NOT NULL DEFAULT 'Activa' CHECK (estado IN ('Activa', 'Inactiva'))
);

-- 3. Tabla Producto
CREATE TABLE IF NOT EXISTS public.producto (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    precio DECIMAL(10,2) NOT NULL CHECK (precio > 0),
    stock INT NOT NULL DEFAULT 0 CHECK (stock >= 0),
    imagen VARCHAR(255),
    estado VARCHAR(15) NOT NULL DEFAULT 'Activo' CHECK (estado IN ('Activo', 'Agotado', 'Inactivo')),
    fecha_creacion DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_actualizacion DATE,
    id_categoria BIGINT NOT NULL REFERENCES public.categoria(id_categoria) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- 4. Tabla Carrito
CREATE TABLE IF NOT EXISTS public.carrito (
    id_carrito BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL UNIQUE REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    fecha_creacion DATE NOT NULL DEFAULT CURRENT_DATE,
    estado VARCHAR(20) NOT NULL DEFAULT 'Vacio' CHECK (estado IN ('Vacio', 'Con Productos', 'Confirmado'))
);

-- 5. Tabla Item Carrito
CREATE TABLE IF NOT EXISTS public.item_carrito (
    id_item BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carrito BIGINT NOT NULL REFERENCES public.carrito(id_carrito) ON UPDATE CASCADE ON DELETE CASCADE,
    id_producto BIGINT NOT NULL REFERENCES public.producto(id_producto) ON UPDATE CASCADE ON DELETE RESTRICT,
    cantidad INT NOT NULL CHECK (cantidad > 0),
    precio_unitario DECIMAL(10,2) NOT NULL CHECK (precio_unitario > 0),
    subtotal DECIMAL(10,2) NOT NULL CHECK (subtotal >= 0),
    CONSTRAINT uq_carrito_producto_sb UNIQUE (id_carrito, id_producto)
);

-- 6. Tabla Direccion Entrega
CREATE TABLE IF NOT EXISTS public.direccion_entrega (
    id_direccion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    nombre_receptor VARCHAR(255) NOT NULL,
    direccion VARCHAR(500) NOT NULL,
    ciudad VARCHAR(100) NOT NULL,
    telefono VARCHAR(255) NOT NULL
);

-- 7. Tabla Pedido (Sello Criptográfico Ley N° 164)
CREATE TABLE IF NOT EXISTS public.pedido (
    id_pedido BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_pedido VARCHAR(20) NOT NULL UNIQUE,
    id_usuario BIGINT NOT NULL REFERENCES public.usuario(id_usuario) ON UPDATE CASCADE ON DELETE RESTRICT,
    id_direccion BIGINT NOT NULL REFERENCES public.direccion_entrega(id_direccion) ON UPDATE CASCADE ON DELETE RESTRICT,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    estado VARCHAR(20) NOT NULL DEFAULT 'Pendiente' CHECK (estado IN ('Pendiente', 'Confirmado', 'Preparando', 'Entregado', 'Rechazado')),
    total DECIMAL(10,2) NOT NULL DEFAULT 0 CHECK (total >= 0),
    hash_integridad VARCHAR(64) NOT NULL DEFAULT '0000000000000000000000000000000000000000000000000000000000000000'
);

-- 8. Tabla Detalle Pedido
CREATE TABLE IF NOT EXISTS public.detalle_pedido (
    id_detalle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido BIGINT NOT NULL REFERENCES public.pedido(id_pedido) ON UPDATE CASCADE ON DELETE CASCADE,
    id_producto BIGINT NOT NULL REFERENCES public.producto(id_producto) ON UPDATE CASCADE ON DELETE RESTRICT,
    cantidad INT NOT NULL CHECK (cantidad > 0),
    precio_unitario DECIMAL(10,2) NOT NULL CHECK (precio_unitario > 0),
    subtotal DECIMAL(10,2) NOT NULL CHECK (subtotal >= 0)
);

-- 9. Tabla Logs Auditoria (Inalterable - Cumplimiento ASFI)
CREATE TABLE IF NOT EXISTS public.logs_auditoria (
    id_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT REFERENCES public.usuario(id_usuario) ON DELETE SET NULL,
    ip_origen VARCHAR(45) NOT NULL,
    user_agent TEXT,
    accion VARCHAR(60) NOT NULL,
    entidad_afectada VARCHAR(50) NOT NULL,
    id_entidad VARCHAR(50),
    detalles JSONB,
    hash_integridad VARCHAR(64) NOT NULL,
    fecha_utc TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Trigger de Inalterabilidad
CREATE OR REPLACE FUNCTION public.fn_prevent_audit_tampering()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'VIOLACIÓN DE SEGURIDAD ASFI: La tabla logs_auditoria es estrictamente inalterable (Append-Only).';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_prevent_audit_tampering ON public.logs_auditoria;
CREATE TRIGGER trg_prevent_audit_tampering
    BEFORE UPDATE OR DELETE ON public.logs_auditoria
    FOR EACH ROW
    EXECUTE FUNCTION public.fn_prevent_audit_tampering();

-- Enable Row Level Security (RLS)
ALTER TABLE public.usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categoria ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.producto ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carrito ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.item_carrito ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.direccion_entrega ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedido ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detalle_pedido ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs_auditoria ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Catalogo publico" ON public.producto FOR SELECT USING (estado != 'Inactivo');
CREATE POLICY "Categorias publicas" ON public.categoria FOR SELECT USING (estado = 'Activa');
CREATE POLICY "Auditoria solo lectura admin" ON public.logs_auditoria FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auditoria solo insercion" ON public.logs_auditoria FOR INSERT TO authenticated WITH CHECK (true);
